version: "3.7"
services:
  db:
    image: mongo:latest
    restart: always
    ports:
      - 27017:27017
    container_name: db-app
    environment:
      MONGODB_INITDB_ROOT_USERNAME: ${DB_USER}
      MONGODB_INITDB_DATABASE: ${DB_NAME}
      MONGODB_INITDB_ROOT_PASSWORD: ${DB_PASS}
    networks:
      - survey-net

  client:
    build:
      context: ./
      dockerfile: survey_frontend.df
    image: stmik-amik-bandung/survey-frontend
    ports:
      - 3001:3000
    container_name: frontend-app
    restart: always
    environment:
      REACT_APP_BASE_URL_API: ${API_URL}
    volumes:
      - ./SURVEY-STMIK-AMIK-BANDUNG:/app
      - /app/node_modules
    stdin_open: true
    networks:
      - survey-net

  server:
    build:
      context: ./
      dockerfile: survey_backend.df
    image: stmik-amik-bandung/survey-backend
    ports:
      - 9000:80
    environment:
      SERVER_PORT: ${SERVER_PORT}
      LIMIT_TRANSFER: ${LIMIT_TRANSFER}
      CLIENT_URL: ${CLIENT_URL}
      ACCESS_TOKEN: ${ACCESS_TOKEN}
      DB_NAME: ${DB_NAME}
      DB_URI: db
      DB_HOST: db:27017
    container_name: backend-app
    restart: always
    volumes:
      - ./BACKEND-SMTIK-AMIK-SURVEY:/server
      - /server/node_modules
    depends_on:
      - db
    networks:
      - survey-net

#  ngrok:
networks:
  survey-net:
    driver: bridge
